/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();
        tampilkanData1();
        tampilkanData2();
        tampilkanData3();
        tampilkanData();
        tglskrg();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTGL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCurtomer = new javax.swing.JTable();
        idl = new javax.swing.JTextField();
        idk = new javax.swing.JTextField();
        idc = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLeptop = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblKariyawan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Transaksi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        id.setEnabled(false);
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 81, -1));

        jLabel2.setText("ID Karyawan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        jLabel3.setText("ID Customer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        jLabel4.setText("ID Leptop");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        btnBaru.setText("Tambah Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });
        jPanel1.add(btnBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 134, -1));

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 774, 100));

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Form Transaksi");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel5)
                .addContainerGap(324, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 774, -1));

        jLabel6.setText("Tanggal Transaksi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtTGL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTGL.setEnabled(false);
        jPanel1.add(txtTGL, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 134, -1));

        jLabel7.setText("Harga");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtHarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtHarga.setEnabled(false);
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 134, -1));

        jLabel8.setText("Qty");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });
        jPanel1.add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 137, -1));

        jLabel9.setText("Total Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel1.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 137, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Customer"));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCurtomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCurtomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCurtomerMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCurtomer);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 110));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 250, 140));

        idl.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idl.setEnabled(false);
        jPanel1.add(idl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 81, -1));

        idk.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idk.setEnabled(false);
        jPanel1.add(idk, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 81, -1));

        idc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idc.setEnabled(false);
        jPanel1.add(idc, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 81, -1));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Leptop"));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLeptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLeptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeptopMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLeptop);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 400, 130));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Karyawan"));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKariyawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKariyawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKariyawanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblKariyawan);

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 230, 110));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 250, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void kosongkanForm() {
        idk.setText("");
        idc.setText("");
        idl.setText("");
        txtHarga.setText("");
        txtQty.setText("");
        txtTGL.setText("");
        txtTotal.setText("");
        cari.setText("");
    }
    
    public void cari(String keyword){
        String [] kolom ={"ID Tra", "Nama Karyawan", "Nama Customer", "Merek", "Harga", "Tanggal Tra", "QTY", "Total Harga", };
        ArrayList<Transaksi> list = new Transaksi().search(keyword);
        Object rowData[] = new Object[8];
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Transaksi k : list){
            rowData[0] = k.getIdTra();
            rowData[1] = k.getK().getNama();
            rowData[2] = k.getC().getNama();
            rowData[3] = k.getMerek();
            rowData[4] = k.getL().getHarga();
            rowData[5] = k.getTgl();
            rowData[6] = k.getQty();
            rowData[7] = k.getTotal();
            
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
        }
    }
    
    private void tampilkanData(){
        String [] kolom ={"ID Tra", "Nama Karyawan", "Nama Customer", "Merek", "Harga", "Tanggal Tra", "QTY", "Total Harga", };
        ArrayList<Transaksi> list = new Transaksi().getAll();
        Object rowData[] = new Object[8];
        
        if(id.getText().equals("")){
            id.setText("1");
        }
        
        
        tblTransaksi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Transaksi k : list){
            rowData[0] = k.getIdTra();
            rowData[1] = k.getK().getNama();
            rowData[2] = k.getC().getNama();
            rowData[3] = k.getMerek();
            rowData[4] = k.getL().getHarga();
            rowData[5] = k.getTgl();
            rowData[6] = k.getQty();
            rowData[7] = k.getTotal();
            
            ((DefaultTableModel)tblTransaksi.getModel()).addRow(rowData);
            id.setText(Integer.toString(k.getIdTra()+1));
            tglskrg();
        }
    }
    
    private void tampilkanData1() {
        String [] kolom ={"ID ", "Nama"};
        ArrayList<Customer> list = new Customer().getAll();
        Object rowData[] = new Object[2];
        
        tblCurtomer.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Customer k : list){
            rowData[0] = k.getId();
            rowData[1] = k.getNama();
            
            ((DefaultTableModel)tblCurtomer.getModel()).addRow(rowData);
        }
    }
    
    private void tampilkanData2() {
        String [] kolom ={"ID ", "Nama"};
        ArrayList<Karyawan> list = new Karyawan().getAll();
        Object rowData[] = new Object[2];
        
        tblKariyawan.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Karyawan k : list){
            rowData[0] = k.getId();
            rowData[1] = k.getNama();
            
            ((DefaultTableModel)tblKariyawan.getModel()).addRow(rowData);
        }
    }
    
    public void tampilkanData3(){
        String [] kolom ={"ID", "Merek", "OS", "Warna", "Harga", "Stok"};
        ArrayList<Transaksi> list = new Transaksi().getAlllep();
        Object rowData[] = new Object[6];
        
        tblLeptop.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Transaksi lg : list){
            rowData[0] = lg.getL().getIdLep();
            rowData[1] = lg.getMerek();
            rowData[2] = lg.getOS();
            rowData[3] = lg.getL().getWarna();
            rowData[4] = lg.getL().getHarga();
            rowData[5] = lg.getL().getStok();
            
            ((DefaultTableModel)tblLeptop.getModel()).addRow(rowData);
        }
    }    
    
     public void tglskrg() {
        Date skrg = new Date();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String tgl = format.format(skrg);
        txtTGL.setText(format.format(skrg));
    }
     
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        Transaksi k = new Transaksi();

        k.setIdTra(Integer.parseInt(id.getText()));
        k.getK().setId(Integer.parseInt(idk.getText()));
        k.getC().setId(Integer.parseInt(idc.getText()));
        k.getL().setIdLep(Integer.parseInt(idl.getText()));
        k.setQty(Integer.parseInt(txtQty.getText()));
        k.setTgl(txtTGL.getText());
        k.setTotal(Integer.parseInt(txtTotal.getText()));


        k.save();
        tampilkanData();
        kosongkanForm();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();

        Transaksi kat = new Transaksi().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        kat.delete();

        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        cari(cari.getText());
    }//GEN-LAST:event_btncariActionPerformed

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblTransaksi.getModel();
        int row = tblTransaksi.getSelectedRow();

        Transaksi kat = new Transaksi().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        idk.setText(String.valueOf(kat.getK().getId()));
        idc.setText(String.valueOf(kat.getC().getId()));
        idl.setText(String.valueOf(kat.getL().getIdLep()));

        id.setText(model.getValueAt(row, 0).toString());
        txtHarga.setText(model.getValueAt(row, 4).toString());
        txtTGL.setText(model.getValueAt(row, 5).toString());
        txtQty.setText(model.getValueAt(row, 6).toString());
        txtTotal.setText(model.getValueAt(row, 7).toString());
        
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void tblCurtomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCurtomerMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblCurtomer.getModel();
        int row = tblCurtomer.getSelectedRow();

        Customer kat = new Customer().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));

        idc.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblCurtomerMouseClicked

    private void tblLeptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeptopMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblLeptop.getModel();
        int row = tblLeptop.getSelectedRow();

        Transaksi kat = new Transaksi().getByIdlep(Integer.parseInt(model.getValueAt(row, 0).toString()));

        idl.setText(model.getValueAt(row, 0).toString());
        txtHarga.setText(model.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tblLeptopMouseClicked

    private void tblKariyawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKariyawanMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblKariyawan.getModel();
        int row = tblKariyawan.getSelectedRow();

        Karyawan kat = new Karyawan().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));

        idk.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblKariyawanMouseClicked

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyReleased
        // TODO add your handling code here:        
        int h = Integer.parseInt(txtHarga.getText());
        int q = Integer.parseInt(txtQty.getText());
        int mk = h*q;
        String rata1 = String.valueOf(mk);
        txtTotal.setText(rata1);
    }//GEN-LAST:event_txtQtyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncari;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idk;
    private javax.swing.JTextField idl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblCurtomer;
    private javax.swing.JTable tblKariyawan;
    private javax.swing.JTable tblLeptop;
    private javax.swing.JTable tblTransaksi;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtTGL;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
