/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package frontend;

import backend.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author User
 */
public class FormLeptopGaming extends javax.swing.JFrame {

    /**
     * Creates new form FormLeptopGaming
     */
    public FormLeptopGaming() {
        initComponents();
        kosongkanForm();
        tampilkanData();
        tampilkanData1();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id = new javax.swing.JTextField();
        idSpek = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtmerek = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtOS = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtWarna = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtBobot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLeptop = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSpesifikasi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        id.setEnabled(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 49, 81, -1));

        idSpek.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        idSpek.setEnabled(false);
        jPanel1.add(idSpek, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 75, 134, -1));

        jLabel3.setText("Merek");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));
        jPanel1.add(txtmerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 101, 134, -1));

        jLabel4.setText("Sistem Os");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel1.add(txtOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 127, 134, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        btnBaru.setText("Tambah Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });
        jPanel1.add(btnBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 134, -1));

        btncari.setText("Cari");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel1.add(btncari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jLabel2.setText("ID Spesifikasi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        jLabel6.setText("Warna");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 156, -1, -1));
        jPanel1.add(txtWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 153, 134, -1));

        jLabel7.setText("Bobot");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, -1, -1));
        jPanel1.add(txtBobot, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 179, 134, -1));

        jLabel8.setText("Kg");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 182, -1, -1));

        jLabel9.setText("Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));
        jPanel1.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 205, 134, -1));
        jPanel1.add(txtStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 231, 134, -1));

        jLabel10.setText("Stok");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 234, -1, -1));

        jLabel11.setText("Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 208, -1, -1));

        jLabel12.setText("ID Leptop");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Form Leptop Gaming");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(278, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(219, 219, 219))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, -1));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Leptop"));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLeptop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLeptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLeptopMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLeptop);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 460, 100));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 480, 130));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Spesifikasi"));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSpesifikasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSpesifikasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSpesifikasiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSpesifikasi);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 373, 98));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 400, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void kosongkanForm(){
        idSpek.setText("");
        txtmerek.setText("");
        txtOS.setText("");
        txtWarna.setText("");
        txtBobot.setText("");
        txtHarga.setText("");     
        txtStok.setText("");
        cari.setText("");
    }
    
    public void tampilkanData(){
        String [] kolom ={"ID", "Merek", "Sistem Operasi", "Warna", "Bobot", "Harga", "Stok"};
        ArrayList<LeptopGaming> list = new LeptopGaming().getAll();
        Object rowData[] = new Object[7];
        
        if(id.getText().equals("")){
            id.setText("1");
        }
        
        
        tblLeptop.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(LeptopGaming lg : list){
            rowData[0] = lg.getIdlepg();
            rowData[1] = lg.getMerek();
            rowData[2] = lg.getOS();
            rowData[3] = lg.getWarna();
            rowData[4] = lg.getBobot();
            rowData[5] = lg.getHarga();
            rowData[6] = lg.getStok();
            
            ((DefaultTableModel)tblLeptop.getModel()).addRow(rowData);
            getIdC();
        }
    }
    
    public void tampilkanData1(){
        String [] kolom ={"ID", "Prosesor", "Ram", "Penyimpanan"};
        ArrayList<Spesifikasi> list = new Spesifikasi().getAll();
        Object rowData[] = new Object[4];
        
        tblSpesifikasi.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(Spesifikasi s : list){
            rowData[0] = s.getIdSpesifikasi();
            rowData[1] = s.getProsesor();
            rowData[2] = s.getRam();
            rowData[3] = s.getPenyimpanan();
            ((DefaultTableModel)tblSpesifikasi.getModel()).addRow(rowData);
        }
    }
    
    public void cari(String keyword){
        String [] kolom ={"ID", "Merek", "Sistem Operasi", "Warna", "Bobot", "Harga", "Stok"};
        ArrayList<LeptopGaming> list = new LeptopGaming().search(keyword);
        Object rowData[] = new Object[7];
        
        tblLeptop.setModel(new DefaultTableModel(new Object[][] {}, kolom));
        
        for(LeptopGaming lg : list){
            rowData[0] = lg.getIdlepg();
            rowData[1] = lg.getMerek();
            rowData[2] = lg.getOS();
            rowData[3] = lg.getWarna();
            rowData[4] = lg.getBobot();
            rowData[5] = lg.getHarga();
            rowData[6] = lg.getStok();
            
            ((DefaultTableModel)tblLeptop.getModel()).addRow(rowData);
        }
    }
    
    public void getIdC(){
        ResultSet rs = DBHelper.selectQuery("select * from leptop");
        try {
            while (rs.next()) {
                id.setText(String.valueOf(rs.getInt("idleptop")+1));
            }
        } catch (SQLException ex) {
        }
    }
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        LeptopGaming lg = new LeptopGaming();
        
        lg.setIdlepg(Integer.parseInt(id.getText()));
        lg.getSpek().setIdSpesifikasi(Integer.parseInt(idSpek.getText()));
        lg.setMerek(txtmerek.getText());
        lg.setOS(txtOS.getText());
        lg.setWarna(txtWarna.getText());
        lg.setBobot(Integer.parseInt(txtBobot.getText()));
        lg.setHarga(Integer.parseInt(txtHarga.getText()));
        lg.setStok(Integer.parseInt(txtStok.getText()));
        
        lg.save();
        tampilkanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblLeptop.getModel();
        int row = tblLeptop.getSelectedRow();

        LeptopGaming kat = new LeptopGaming().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        kat.delete();
        
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        kosongkanForm();
        tampilkanData();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        cari(cari.getText());
    }//GEN-LAST:event_btncariActionPerformed

    private void tblLeptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLeptopMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblLeptop.getModel();
        int row = tblLeptop.getSelectedRow();

        LeptopGaming lg = new LeptopGaming().getById(Integer.parseInt(model.getValueAt(row, 0).toString()));
        idSpek.setText(String.valueOf(lg.getSpek().getIdSpesifikasi()));
        
        id.setText(model.getValueAt(row, 0).toString());
        txtmerek.setText(model.getValueAt(row, 1).toString());
        txtOS.setText(model.getValueAt(row, 2).toString());
        txtWarna.setText(model.getValueAt(row, 3).toString());
        txtBobot.setText(model.getValueAt(row, 4).toString());
        txtHarga.setText(model.getValueAt(row, 5).toString());
        txtStok.setText(model.getValueAt(row, 6).toString());
    }//GEN-LAST:event_tblLeptopMouseClicked

    private void tblSpesifikasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSpesifikasiMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)tblSpesifikasi.getModel();
        int row = tblSpesifikasi.getSelectedRow();

        idSpek.setText(model.getValueAt(row, 0).toString());
    }//GEN-LAST:event_tblSpesifikasiMouseClicked

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLeptopGaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLeptopGaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLeptopGaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLeptopGaming.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLeptopGaming().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btncari;
    private javax.swing.JTextField cari;
    private javax.swing.JTextField id;
    private javax.swing.JTextField idSpek;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JTable tblLeptop;
    private javax.swing.JTable tblSpesifikasi;
    private javax.swing.JTextField txtBobot;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtOS;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtWarna;
    private javax.swing.JTextField txtmerek;
    // End of variables declaration//GEN-END:variables
}
